ipc = Portafolio()
ipc.anio_validez = 2014
ipc.composicion = [
    {'emisora': 'AC', 'peso': 1.12},
    {'emisora': 'ALFA', 'peso': 5.72},
    {'emisora': 'ALPEK', 'peso': 0.40},
    {'emisora': 'ALSEA', 'peso': 0.81},
    {'emisora': 'AMX', 'peso': 16.44},
    {'emisora': 'ASUR', 'peso': 1.25},
    {'emisora': 'BIMBO', 'peso': 1.79},
    {'emisora': 'BOLSA', 'peso': 0.38},
    {'emisora': 'CEMEX', 'peso': 7.29},
    {'emisora': 'COMERCI', 'peso': 0.79},
    {'emisora': 'ELEKTRA', 'peso': 1.14},
    {'emisora': 'FEMSA', 'peso': 7.79},
    {'emisora': 'GAP', 'peso': 0.86},
    {'emisora': 'GCARSO', 'peso': 0.82},
    {'emisora': 'GENTERA', 'peso': 0.96},
    {'emisora': 'GFINBUR', 'peso': 2.45},
    {'emisora': 'GFNORTE', 'peso': 8.11},
    {'emisora': 'GFREFIO', 'peso': 0.27},
    {'emisora': 'FMEXICO', 'peso': 6.94},
    {'emisora': 'GRUMA', 'peso': 1.13},
    {'emisora': 'ICA', 'peso': 0.49},
    {'emisora': 'ICH', 'peso': 0.39},
    {'emisora': 'IENOVA', 'peso': 0.65},
    {'emisora': 'KIMBER', 'peso': 1.81},
    {'emisora': 'KOF', 'peso': 2.54},
    {'emisora': 'LAB', 'peso': 1.0},
    {'emisora': 'LALA', 'peso': 0.73},
    {'emisora': 'LIVEPOL', 'peso': 0.99},
    {'emisora': 'MEXCHEM', 'peso': 1.94},
    {'emisora': 'OHLMEX', 'peso': 1.00},
    {'emisora': 'PE&OLES', 'peso': 1.27},
    {'emisora': 'PINFRA', 'peso': 1.50},
    {'emisora': 'SANMEX', 'peso': 2.36},
    {'emisora': 'TLEVISA', 'peso': 8.45},
    {'emisora': 'WALMEX', 'peso': 6.43},
]
